# Generated by Django 5.1.4 on 2024-12-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_text', models.CharField(max_length=10, unique=True)),
                ('unix_timestamp', models.IntegerField(default=0)),
                ('bid_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ask_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('spot_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_change_24hr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
